### ISSUE TITLE
Why do you use UTXO_DUST size for output? it will cause lose all assets.

### ISSUE THREAD

**Issue by lolieatapple** [unisat-wallet/wallet-sdk#2]
https://github.com/unisat-wallet/wallet-sdk/blob/674801bbdd0d542ea3bd662572582bc89f53c32c/src/tx-helpers/send-btc.ts#L68

Why do you use UTXO_DUST size for output in sendAllBTC function? it will cause lose all assets.

**Comment by huanniangstudio** [comment]
This is just a dummy and will be adjusted to the correct amount later.
